export const creatures = [
  {
    name: "Bat",
    challengerating: "0",
    type: "Beast",
    size: "Tiny",
    alignment: "Unaligned",
    creature: "Misc Creature",
    environment: "None",
  },

  {
    name: "Raven",
    challengerating: "0",
    type: "Beast",
    size: "Tiny",
    alignment: "Unaligned",
    creature: "Misc Creature",
    environment: "Hill,Swamp,Urban",
  },

  {
    name: "Rat",
    challengerating: "0",
    type: "Beast",
    size: "Tiny",
    alignment: "Unaligned",
    creature: "Misc Creature",
    environment: "Swamp,Urban",
  },

  {
    name: "Scorpion",
    challengerating: "0",
    type: "Beast",
    size: "Tiny",
    alignment: "Unaligned",
    creature: "Misc Creature",
    environment: "Desert",
  },

  {
    name: "Seal",
    challengerating: "0",
    type: "Beast",
    size: "Medium",
    alignment: "Unaligned",
    creature: "Misc Creature",
    environment: "None",
  },
  {
    name: "Badger",
    challengerating: "0",
    type: "Beast",
    size: "Tiny",
    alignment: "Unaligned",
    creature: "Misc Creature",
    environment: "Forest",
  },
  {
    name: "Sheep",
    challengerating: "0",
    type: "Beast",
    size: "Small",
    alignment: "Unaligned",
    creature: "Misc Creature",
    environment: "Grassland,Hill,Urban,Mountain",
  },
  {
    name: "Spider",
    challengerating: "0",
    type: "Beast",
    size: "Medium",
    alignment: "Unaligned",
    creature: "Misc Creature",
    environment: "None",
  },
  {
    name: "Cat",
    challengerating: "0",
    type: "Beast",
    size: "Tiny",
    alignment: "Unaligned",
    creature: "Misc Creature",
    environment: "Desert,Forest,Grassland,Urban",
  },
  {
    name: "Crab",
    challengerating: "0",
    type: "Beast",
    size: "Tiny",
    alignment: "Unaligned",
    creature: "Misc Creature",
    environment: "Coastal",
  },
];
