import * as React from "react";
import { useForm, SubmitHandler } from "react-hook-form";
import Head from "next/head";
import { Inter } from "@next/font/google";
import { creatures } from "./creatures";
import {
  Box,
  Card,
  CardBody,
  Grid,
  GridItem,
  Divider,
  List,
  ListItem,
  Heading,
  Textarea,
  Checkbox,
  Flex,
  VStack,
  HStack,
  Select,
  Input,
  Button,
  Text,
  chakra,
} from "@chakra-ui/react";
import styled from "@emotion/styled";
import { InputStatCard } from "../../components/input-stat-card";
import { InputLabelCard } from "../../components/input-label-card";
import { CheckboxGroupCard } from "../../components/checkbox-group-card";
import { attackTypes } from "../../data/attack-types";
import { languages } from "../../data/languages";
import { equippedItems } from "../../data/equipped-items";
import { LabelInput } from "../../components/label-input";

const CharacterCard = styled(Card)`
  margin-top: 10px;
  padding: 10px;
`;
// Primary div container element
const Primary = styled.div`
  margin: 20px;
`;

const inter = Inter({ subsets: ["latin"] });

const rowIndexes = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

// TODO: offload to our database
const listItems = [
  {
    title: "STR",
    quantifier: 0,
  },
  {
    title: "DEX",
    quantifier: 0,
  },
  {
    title: "CON",
    quantifier: 0,
  },
  {
    title: "INT",
    quantifier: 0,
  },
  {
    title: "WIS",
    quantifier: 0,
  },
  {
    title: "CHA",
    quantifier: 0,
  },
];

export type CharacterSheetInputs = {
  [key: string]: string;
};

export default function Character() {
  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm<CharacterSheetInputs>();
  const onSubmit: SubmitHandler<CharacterSheetInputs> = (data) => {
    debugger;

    console.log(data);
  };

  // JSX is really the view-layer (put any data or logic above this)
  return (
    <>
      <Head>
        <title>Monster Database</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Primary>
          <form onSubmit={handleSubmit(onSubmit)}>
            <Heading>Monster Database</Heading>
            <Button mt={4} colorScheme="teal" type="search">
              Search
            </Button>
            <Box>
              <Grid gridTemplateColumns="repeat(6, 1fr)" gap={5}>
                <GridItem w="100%">
                  <LabelInput
                    registerId="monsterName"
                    register={register}
                    label="Monster Name:"
                  />
                </GridItem>
                <GridItem w="100%" pr="15px">
                  <LabelInput
                    registerId="playerName"
                    register={register}
                    label="Size:"
                  />
                </GridItem>
                <GridItem w="100%">
                  <LabelInput
                    registerId="environment"
                    register={register}
                    label="Environment:"
                  />
                </GridItem>
                <GridItem w="100%" pr={"15px"}>
                  <LabelInput
                    registerId="challenge"
                    register={register}
                    label="Challenge:"
                  />
                </GridItem>
                <GridItem w="100%">
                  <LabelInput
                    registerId="monsterType"
                    register={register}
                    label="Type:"
                  />
                </GridItem>
                <GridItem w="100%">
                  <LabelInput
                    registerId="alignment"
                    register={register}
                    label="Alignment:"
                  />
                </GridItem>
                <GridItem w="100%">
                  <LabelInput
                    registerId="armorClass"
                    register={register}
                    label="Armor Class:"
                  />
                </GridItem>
                <GridItem w="100%">
                  <LabelInput
                    registerId="avgHitPoints"
                    register={register}
                    label="Avg Hit Points:"
                  />
                </GridItem>
                <GridItem w="100%">
                  <LabelInput
                    registerId="senses"
                    register={register}
                    label="Senses:"
                  />
                </GridItem>
                <GridItem w="100%">
                  <LabelInput
                    registerId="skillProficiency"
                    register={register}
                    label="Skill Proficiency:"
                  />
                </GridItem>
                <GridItem w="100%">
                  <LabelInput
                    registerId="legendary"
                    register={register}
                    label="Legendary:"
                  />
                </GridItem>
                <GridItem w="100%">
                  <LabelInput
                    registerId="mythic"
                    register={register}
                    label="Mythic:"
                  />
                </GridItem>
                <GridItem w="100%">
                  <LabelInput
                    registerId="hasLair"
                    register={register}
                    label="Has Lair:"
                  />
                </GridItem>
                <GridItem w="100%">
                  <LabelInput
                    registerId="resistance"
                    register={register}
                    label="Resistance:"
                  />
                </GridItem>
                <GridItem w="100%">
                  <LabelInput
                    registerId="damageImmunity"
                    register={register}
                    label="Damage Immunity:"
                  />
                </GridItem>
                <GridItem w="100%">
                  <LabelInput
                    registerId="conditionImmunity"
                    register={register}
                    label="Condition Immunity:"
                  />
                </GridItem>
                <GridItem w="100%">
                  <LabelInput
                    registerId="vulnerability"
                    register={register}
                    label="Vulnerability:"
                  />
                </GridItem>
                <GridItem w="100%">
                  <LabelInput
                    registerId="languages"
                    register={register}
                    label="Languages:"
                  />
                </GridItem>
                <GridItem w="100%">
                  <LabelInput
                    registerId="movementType"
                    register={register}
                    label="Movement Type:"
                  />
                </GridItem>
                <GridItem w="100%">
                  <LabelInput
                    registerId="monsterTags"
                    register={register}
                    label="Monster Tags:"
                  />
                </GridItem>
                <GridItem w="100%">
                  <LabelInput
                    registerId="monsterSubTypes"
                    register={register}
                    label="Monsters Sub-Types:"
                  />
                </GridItem>
              </Grid>
            </Box>
          </form>
        </Primary>
      </main>
    </>
  );
}
