import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import {
  Card,
  CardHeader,
  CardBody,
  CardFooter,
  Grid,
  GridItem,
  Button,
  ButtonGroup,
  Divider,
  Heading,
  Stack,
  color,
} from "@chakra-ui/react";
import { Box } from "@chakra-ui/react";
import {
  List,
  Badge,
  ListItem,
  ListIcon,
  OrderedList,
  UnorderedList,
  Text,
} from "@chakra-ui/react";
import styled from "@emotion/styled";
import { StatCard } from "../../components/stat-card";

const CharacterCard = styled(Card)`
  margin-top: 10px;
  padding: 10px;
`;
// Primary div container element
const Primary = styled.div`
  margin: 20px;
`;

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const listItems = [
    {
      title: "STR",
      quantifier: 0,
    },
    {
      title: "DEX",
      quantifier: 0,
    },
    {
      title: "CON",
      quantifier: 0,
    },
    {
      title: "INT",
      quantifier: 0,
    },
    {
      title: "WIS",
      quantifier: 0,
    },
    {
      title: "CHA",
      quantifier: 0,
    },
  ];

  // JSX is really the view-layer (put any data or logic above this)
  return (
    <>
      <Head>
        <title>Character Sheet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Primary>
          <Heading>Character Sheet</Heading>
          <Grid templateColumns="repeat(3, 1fr)" gap={10}>
            <GridItem w="100%">
              <CharacterCard textAlign="center" fontWeight="bold">
                <Grid
                  templateAreas={`
                  "stat next"
                  "footer footer"`}
                  gridTemplateColumns={"70px 1fr"}
                  gap="1"
                  fontWeight="bold"
                >
                  <GridItem pl="2" area={"stat"}>
                    <List>
                      {listItems.map(({ title }) => {
                        return (
                          <ListItem key={`list-item-${title}`}>
                            <StatCard title={title} />
                          </ListItem>
                        );
                      })}
                    </List>
                  </GridItem>
                  <GridItem pl="2" bg="green.300" area={"next"}>
                    <Card>
                      <Box>Inspiration</Box>
                    </Card>
                    <Card>Proficiency Bonus</Card>
                    <Card>
                      <Box>Strength</Box>
                      <Box>Dexterity</Box>
                      <Box>Constitution</Box>
                      <Box>Intelligence</Box>
                      <Box>Wisdom</Box>
                      <Box>Charisma</Box>
                      Saving Throws
                    </Card>
                    <Card>
                      <Box>Acrobatics</Box>
                      <Box>Animal Handling</Box>
                      <Box>Arcana</Box>
                      <Box>Athletics</Box>
                      <Box>Deception</Box>
                      <Box>History</Box>
                      <Box>Insight</Box>
                      <Box>Intimidation</Box>
                      <Box>Investigator</Box>
                      <Box>Medicine</Box>
                      <Box>Nature</Box>
                      <Box>Perception</Box>
                      <Box>Performance</Box>
                      <Box>Pursuasion</Box>
                      <Box>Religion</Box>
                      <Box>Sleight of Hand</Box>
                      <Box>Stealth</Box>
                      <Box>Survival</Box>
                      Skills
                    </Card>
                  </GridItem>

                  <GridItem pl="2" bg="blue.300" area={"footer"}>
                    PASSIVE WISDOM (PERCEPTION)
                  </GridItem>
                </Grid>
              </CharacterCard>
            </GridItem>
            <GridItem w="100%">
              <CharacterCard>
                <CardBody>
                  <Stack mt="6" spacing="3">
                    <List>
                      <ListItem>AC</ListItem>
                      <ListItem>INIT</ListItem>
                      <ListItem>Current Hit Points</ListItem>
                      <ListItem>Temporary Hit Points</ListItem>
                      <ListItem>HIT DICE</ListItem>
                      <ListItem>DEATH SAVES</ListItem>
                    </List>
                  </Stack>
                </CardBody>
                <Divider />
              </CharacterCard>
            </GridItem>
            <GridItem w="100%">
              <CharacterCard>
                <List>
                  <ListItem>Personality Traits</ListItem>
                  <ListItem>Ideals</ListItem>
                  <ListItem>Bonds</ListItem>
                  <ListItem>Flaws</ListItem>
                  <ListItem>Alignment</ListItem>
                </List>
              </CharacterCard>
            </GridItem>
            <GridItem w="100%">
              <CharacterCard>
                <OrderedList>
                  <ListItem>Strength</ListItem>
                  <ListItem>Dexterity</ListItem>
                  <ListItem>Constitution</ListItem>
                  <ListItem>Intelligence</ListItem>
                </OrderedList>
              </CharacterCard>
            </GridItem>
          </Grid>
        </Primary>
      </main>
    </>
  );
}
