import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { Card, Grid, GridItem } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid
        gridTemplateColumns="20% 20% 20% 20% 20%"
        gridTemplateRows="20% 20% 20% 20% 20%"
        gap={10}
      >
        <GridItem w="100%" bg="green.100" rowSpan={10} ml="20">
          <Card>Player Avatar/Buttons for Character</Card>
        </GridItem>
        <GridItem w="100%" bg="blue.200">
          <Card>Notification</Card>
        </GridItem>
      </Grid>
    </>
  );
}
